### ISSUE TITLE
[3.0] can't install

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#3448]
I get this: 
```php
Loading composer repositories with package information                                                                                                                                 Updating dependencies (including require-dev)         Generating autoload files
Script php artisan clear-compiled handling the post-update-cmd event returned with an erro

  [RuntimeException]
  Error Output:

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]
```

I tried to run mnually:
```php
php artisan clear-compiled
php artisan optimize
composer dumpautoload -o
```

and when going to the website, get: http://pic.webas.lt/webas.lt-H1bxL8Awcv.png

any ideas?

**Comment by RyanThompson** [comment]
What PHP version are you on?

**Comment by philmartinez** [comment]
I'm using Homestead at php version 5.4.30. Actually, I looked again and the installer isn't creating any tables. This is what I get.

    QueryException in Connection.php line 614:
    SQLSTATE[42S02]: Base table or view not found: 1146 Table     'p3.default_addons_modules' doesn't exist (SQL: select * from     `default_addons_modules` where `installed` = 1)

**Comment by huglester** [comment]
What i tried is to run a composer install using php 5.4 and php5.5 binary with same results :(

**Comment by huglester** [comment]
I also trie do download 3.0.0-1alpha archive, extract and run... same results as in the image above: http://pic.webas.lt/webas.lt-H1bxL8Awcv.png

**Comment by RyanThompson** [comment]
Try disabling debug in config/app.php - just learned this morning that there is an issue in there. 

I will update the repo to include that disabled by default.

**Comment by sgoodwin10** [comment]
i am getting the same issue as philmartinez.
latest homestead - PHP 5.6.3

Also had nested Twig issue. had to update /etc/php5/fpm/config.d/20-xdebug.ini and add the following just to get to the install page:
xdebug.max_nesting_level=10000

**Comment by nickb777** [comment]
Had to do the same as sgoodwin10 on Homestead i.e. add xdebug.max_nesting_level = 1000 to /etc/php5/fpm/config.d/20-xdebug.ini

Had the same issue as philmartinez where tables were not getting created during install. FYI, if you put in the wrong table details you get stuck in an error loop (rather than being redirected to the installer settings page).

Eventually managed to get something installed after retrying, but now I'm just getting a blank dashboard:

![image](https://cloud.githubusercontent.com/assets/566519/5814624/69c66676-a085-11e4-8371-2ae7d392b506.png)

**Comment by RyanThompson** [comment]
Dashboard module is a place holder right now.

PS - git pull / composer update. 


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by huglester** [comment]
@RyanThompson I have managed to go a little further.

I have cloned, installed th eprject and disabled the xdebug. so I could get some more errors :)

the problem I see first one is: 
public/assets/default created has very wrong permissions

Even with user who created it I could not access it

**Comment by huglester** [comment]
and when I go to permissions, I get: http://pic.webas.lt/webas.lt-RYlvwLpaLU.png

**Comment by RyanThompson** [comment]
Hey man - I am actively working in this area in order to lock in some Alpha2 requirements. You can correct that path and PR if you want or Ill get to it later today ^_^


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by RyanThompson** [comment]
Directory issues with view compiling are fixed, validation is in now so I can add validation for the database table as well.

**Comment by huglester** [comment]
Sorry dude was a little afk. this month is difficult for me. And I am, as for now, weak at pyro3 part :) 

I tried reinstalling, with the directory problem is still the same:
permissions are: 
dr----x--t 2 pyro23 pyro23 4096 Jan 26 16:01 default

(better view: http://pic.webas.lt/webas.lt-orxBN22K44.png )
I am not sure if I will be able to fix that yet:)))

**Comment by umair2k3** [comment]
I am having installation error.

[Error Exception]
zipArchive::extractTo<>: No such file or directory

Can you please help ??

Help will be highly appreciated.
