### ISSUE TITLE
No labels for fields PyroCMS-beta1

### ISSUE THREAD

**Issue by vizo** [pyrocms/pyrocms#3531]
Module pages and navigation fields without labels. Fresh installation.

![screenshot from 2015-09-01 01-47-14](https://cloud.githubusercontent.com/assets/740240/9593199/f0f1efaa-504b-11e5-9787-8285438bf29e.png)

**Comment by RyanThompson** [comment]
Can you clear composer cache and try again? This should be resolved.

**Comment by vizo** [comment]
I did composer clear-cache + composer update and still the same ...

**Comment by vizo** [comment]
I reinstall it completely and it works. Then i added another locale "Slovene" trough Settings -> Localization. And still worked. Then i changed Default language (What is the default language for your application?) to Slovene, and labels disappear. When i change it back to English, labels are shown again.

So looks like translations are missing, how can i translate it or set fallback?

So this is not default language for application but admin also?

Thanks!

**Comment by RyanThompson** [comment]
It should default to english when not found. There's a bug there..

Translations for all addons and and the core are in resources/lang

Please consider submitting pull requests for Slovene!

**Comment by vizo** [comment]
Also when editing page with multiple locales there is just one field under English (page name) and under Slovene are two same fields (page title) with same name attribute "title_sl". This second title field should be under English with attribute name title_en.

**Comment by RyanThompson** [comment]
Can you check this again? I believe it's fixed.

**Comment by vizo** [comment]
Now localized fields under Page type and page have the same name attribute just "title", no more "title_sl", "title_en", .... So if you input under Slovene tab or English tab, all values becomes the same...

**Comment by RyanThompson** [comment]
This should be resolved. Was the fallback locale getting changed.
