### ISSUE TITLE
Could not run the Installer

### ISSUE THREAD

**Issue by sergey-koretsky** [pyrocms/pyrocms#3532]
after: *composer create-project pyrocms/pyrocms=3.0-beta1 ./www --prefer-dist*
and navigation to local domain to run the installer i got this error:

Whoops, looks like something went wrong.
1/1 ErrorException in AddonServiceProvider.php line 212: Invalid argument supplied for foreach()

    in AddonServiceProvider.php line 212
    at HandleExceptions->handleError('2', 'Invalid argument supplied for foreach()', '/var/www/vhosts/pyrocms.devsrv/www/vendor/anomaly/streams-platform/src/Addon/AddonServiceProvider.php', '212', array('routes' => array())) in AddonServiceProvider.php line 212
    at AddonServiceProvider->getRoutes() in AddonProvider.php line 247
    at AddonProvider->registerRoutes(object(CheckboxesFieldTypeServiceProvider), object(CheckboxesFieldType)) in AddonProvider.php line 135
    at AddonProvider->register(object(CheckboxesFieldType)) in AddonIntegrator.php line 145
    at AddonIntegrator->register('/var/www/vhosts/pyrocms.devsrv/www/core/anomaly/checkboxes-field_type', array(), array()) in AddonManager.php line 122
    at AddonManager->register() in StreamsServiceProvider.php line 214
    at StreamsServiceProvider->Anomaly\Streams\Platform\{closure}(object(Application))
    at call_user_func(object(Closure), object(Application)) in Application.php line 773
    at Application->fireAppCallbacks(array(object(Closure))) in Application.php line 722
    at Application->boot() in BootProviders.php line 17
    at BootProviders->bootstrap(object(Application)) in Application.php line 203
    at Application->bootstrapWith(array('Illuminate\Foundation\Bootstrap\DetectEnvironment', 'Illuminate\Foundation\Bootstrap\LoadConfiguration', 'Illuminate\Foundation\Bootstrap\ConfigureLogging', 'Illuminate\Foundation\Bootstrap\HandleExceptions', 'Illuminate\Foundation\Bootstrap\RegisterFacades', 'Illuminate\Foundation\Bootstrap\RegisterProviders', 'Illuminate\Foundation\Bootstrap\BootProviders')) in Kernel.php line 222
    at Kernel->bootstrap() in Kernel.php line 117
    at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 87
    at Kernel->handle(object(Request)) in index.php line 53

**Comment by RyanThompson** [comment]
Can you try this again? Was likely a small patch issue I pushed during dev.

**Comment by RyanThompson** [comment]
Closing for now or Ill forget but open it back up if it's still a thing.

**Comment by sergey-koretsky** [comment]
unfortunately the same error is still present (so i don't attach the same error log again, but it is the same one)
1. i've just cloned the repo:
 git clone https://github.com/pyrocms/pyrocms.git ./www

2. then composer install from the www folder

and navigate my browser to the root domain (http://pyrocms.devsrv/)

and got the same error
