### ISSUE TITLE
Navigation items do not get parent class

### ISSUE THREAD

**Issue by keevitaja** [pyrocms/pyrocms#3615]
When menu has item1 and borowsing item1/subitem then menu item1 does not get parent class. v2.2 had this feature.

Edit: structure gets active class, menu gets none

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/pages-module/commit/2c89b3a72e5e436a0832543521524ee4e06399b5

**Comment by keevitaja** [comment]
It is not fixed. Now both strcuture and menu do not get classes for parents.

**Comment by keevitaja** [comment]
@RyanThompson please reopen this issue!

**Comment by RyanThompson** [comment]
I can personally vouch that these are working correctly. I've tested on my end. If you have a specific pattern or something that is causing issues please post more details ^_^

**Comment by keevitaja** [comment]
No, it is not working. This is how v2 handles things:

![screenshot_2016-03-14_16-21-01](https://cloud.githubusercontent.com/assets/158787/13747515/425ed1a6-ea01-11e5-9a5a-57eb6d2d4178.png)

This is what happens in v3

![screenshot_2016-03-14_16-23-29](https://cloud.githubusercontent.com/assets/158787/13747572/90c69162-ea01-11e5-9f6a-ee2a8936865f.png)

also http://keevitusseadmed.app/ru/kontakt does not get the current class.
