### ISSUE TITLE
Core assets Path 

### ISSUE THREAD

**Issue by ilessy** [pyrocms/pyrocms#3661]
While on MAC I don't have this problem but when I work on Windows some assets can not be displayed, like the fontawesome fonts. 
```
http://localhost/app/mypyro/assets/%0Core/pyrocms/starter-theme/resources/font-awesome/fonts/fontawesome-webfont.woff?v=4.2.0
```
As you can see, there is a **%0** in the path.

**Comment by ilessy** [comment]
Well after a little dig I found the problem. Some css files have paths like this:
```
font-family: 'Glyphicons Regular';
  src: url('/app/mypyro2/assets/\core/pyrocms/pyrocms-theme/resources/fonts/glyphicons/glyphicons-regular.eot');
```
Notice there is a **\core** in the path and that caused the bug.

**Comment by RyanThompson** [comment]
This should fix it: https://github.com/anomalylabs/streams-platform/commit/2a5348e1ad33164e48b93a4c3c82ead29e9d3692

Thanks for digging! Very helpful.

**Comment by muradshak** [comment]
@RyanThompson . The issue still persist for me. made a fresh install.
