### ISSUE TITLE
PHP Fatal error: Uncaught Twig_Error_Loader: Template "theme::errors/500" is not defined

### ISSUE THREAD

**Issue by Mastersey** [pyrocms/pyrocms#3719]
Hello,

 I can't install pyrocms.
After updating composer (with no error), i start the setup then.... I have this error : http://imgur.com/fwIvTlY

with httpd errors:

`[Fri May 27 13:27:48.108487 2016] [:error] [pid 16938] [client 176.151.214.122:60600] PHP Fatal error:  Uncaught Twig_Error_Loader: Template "theme::errors/500" is not defined (). in /srv/http/pyro/vendor/twig/twig/lib/Twig/Loader/Chain.php:115\nStack trace:\n#0 /srv/http/pyro/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Chain->getCacheKey('theme::errors/5...')\n#1 /srv/http/pyro/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('theme::errors/5...', NULL)\n#2 /srv/http/pyro/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('theme::errors/5...', NULL)\n#3 /srv/http/pyro/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\\Bridge->loadTemplate('theme::errors/5...')\n#4 /srv/http/pyro/vendor/rcrowe/twigbridge/src/Engine/Twig.php(90): TwigBridge\\Engine\\Compiler->load('theme::errors/5...')\n#5 /srv/http/pyro/bootstrap/cache/compiled.php(14586): TwigBridge\\Engine\\Twig->get('theme::errors/5...', Array)\n#6 /srv/http/pyro/bootstrap/cache/compiled.php(14574): Illuminate\\View\\View->getContents()\n#7 /srv/http/pyro/bootstrap/cache/compiled.php(1 in /srv/http/pyro/vendor/rcrowe/twigbridge/src/Engine/Compiler.php on line 101, referer: http://mastersey.net/pyro/public/installer/finish
[Fri May 27 13:27:48.109811 2016] [:error] [pid 16938] [client 176.151.214.122:60600] PHP Fatal error:  Uncaught Twig_Error_Loader: Template "theme::errors/500" is not defined (). in /srv/http/pyro/vendor/twig/twig/lib/Twig/Loader/Chain.php:115\nStack trace:\n#0 /srv/http/pyro/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Chain->getCacheKey('theme::errors/5...')\n#1 /srv/http/pyro/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('theme::errors/5...', NULL)\n#2 /srv/http/pyro/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('theme::errors/5...', NULL)\n#3 /srv/http/pyro/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\\Bridge->loadTemplate('theme::errors/5...')\n#4 /srv/http/pyro/vendor/rcrowe/twigbridge/src/Engine/Twig.php(90): TwigBridge\\Engine\\Compiler->load('theme::errors/5...')\n#5 /srv/http/pyro/bootstrap/cache/compiled.php(14586): TwigBridge\\Engine\\Twig->get('theme::errors/5...', Array)\n#6 /srv/http/pyro/bootstrap/cache/compiled.php(14574): Illuminate\\View\\View->getContents()\n#7 /srv/http/pyro/bootstrap/cache/compiled.php(1 in /srv/http/pyro/vendor/rcrowe/twigbridge/src/Engine/Compiler.php on line 101, referer: http://mastersey.net/pyro/public/installer/finish
`

Any idea please ?

Thank you.

**Comment by RyanThompson** [comment]
What does your Laravel storage log say?

**Comment by RyanThompson** [comment]
@Mastersey was in the finish stage? Im guessing maybe so - in that case it's an issue with seeding. Make sure your database is clean before installing maybe?

**Comment by Mastersey** [comment]
I cleaned up the DB, removed all files then tried again : 

- git clone https://github.com/pyrocms/pyrocms.git pyro
- cd pyro
- composer update
- chown -R http:http ../pyro/
I go to the installer -> http://mastersey.net/pyro/public/installer then : 
* configure MySQL/login/app/timezone...
* Primary Domain: "mastersey.net/pyro/public"
* Click on INSTALL.... Configuring, Installing...

And i have the same error as above (cf screenshot)

Sorry but what's Laravel ?
Where is the log please ?

**Comment by RyanThompson** [comment]
I’ve found it.. Not sure why it’s complaining all of a sudden.

The search indexer uses the Evaluate class which passes the target through Laravel’s data_get() helper. The page for example is indexed for it’s URL like ‘entry.path’ and path is being called as an attribute which - in Laravel will translate to a relation if not defined as an attribute. 

->path() is safe - ->path is not from the model basically.

Very odd. But Im on it.

**Comment by Mastersey** [comment]
Oh so it's not my fault ? Good news for me :-p

**Comment by RyanThompson** [comment]
This should be resolved if you wanna composer update (streams platform should update): https://github.com/anomalylabs/streams-platform/commit/d7ae81af748e50d288bf566f4fc344b9e13fcf85

**Comment by RyanThompson** [comment]
Not keen on why it popped up now.. But, pointed out a good point in the API anyways. Evaluator has no business trying to convert the target to any values. Only evaluates closures.

**Comment by Mastersey** [comment]
Sorry but still the same problem/error after cleaning and retry eveything.

**Comment by RyanThompson** [comment]
Try composer clear-cache or adding the —prefer-source to your composer create project. The commit mentioned above should be applied if you wanna double check your file system.

**Comment by Mastersey** [comment]
Done.

After a new try with : 
`composer create-project pyrocms/pyrocms=3.0-rc2`

=> "Seeding : Page Module" => Then, still the same problem.

```
[Fri May 27 19:14:02.528785 2016] [:error] [pid 22766] [client 176.151.214.122:54228] PHP Fatal error:  Uncaught Twig_Error_Loader: Template "theme::errors/500" is not defined (). in /srv/http/pyrocms/vendor/twig/twig/lib/Twig/Loader/Chain.php:115\nStack trace:\n#0 /srv/http/pyrocms/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Chain->getCacheKey('theme::errors/5...')\n#1 /srv/http/pyrocms/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('theme::errors/5...', NULL)\n#2 /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('theme::errors/5...', NULL)\n#3 /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\\Bridge->loadTemplate('theme::errors/5...')\n#4 /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Engine/Twig.php(90): TwigBridge\\Engine\\Compiler->load('theme::errors/5...')\n#5 /srv/http/pyrocms/bootstrap/cache/compiled.php(14586): TwigBridge\\Engine\\Twig->get('theme::errors/5...', Array)\n#6 /srv/http/pyrocms/bootstrap/cache/compiled.php(14574): Illuminate\\View\\View->getContents()\n#7 /srv/http/pyrocms/boo in /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Engine/Compiler.php on line 101, referer: http://mastersey.net/pyrocms/public/installer/finish
[Fri May 27 19:14:02.529417 2016] [:error] [pid 22766] [client 176.151.214.122:54228] PHP Fatal error:  Uncaught Twig_Error_Loader: Template "theme::errors/500" is not defined (). in /srv/http/pyrocms/vendor/twig/twig/lib/Twig/Loader/Chain.php:115\nStack trace:\n#0 /srv/http/pyrocms/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Chain->getCacheKey('theme::errors/5...')\n#1 /srv/http/pyrocms/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('theme::errors/5...', NULL)\n#2 /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('theme::errors/5...', NULL)\n#3 /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\\Bridge->loadTemplate('theme::errors/5...')\n#4 /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Engine/Twig.php(90): TwigBridge\\Engine\\Compiler->load('theme::errors/5...')\n#5 /srv/http/pyrocms/bootstrap/cache/compiled.php(14586): TwigBridge\\Engine\\Twig->get('theme::errors/5...', Array)\n#6 /srv/http/pyrocms/bootstrap/cache/compiled.php(14574): Illuminate\\View\\View->getContents()\n#7 /srv/http/pyrocms/boo in /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Engine/Compiler.php on line 101, referer: http://mastersey.net/pyrocms/public/installer/finish
```

**Comment by RyanThompson** [comment]
Does this class match in your installation? 

https://github.com/anomalylabs/streams-platform/blob/master/src/Support/Evaluator.php <https://github.com/anomalylabs/streams-platform/blob/master/src/Support/Evaluator.php>

**Comment by RyanThompson** [comment]
I was originally able to recreate this issue but the fix was confirmed. Double check that file - maybe clear composer cache. Should be good to go!

**Comment by Mastersey** [comment]
I cleared the cache already :(
I'm searching for the Evaluator.php file in my system to compare it, i'll tell you.

**Comment by bloveless** [comment]
I was able to do a fresh install using

    composer create-project pyrocms/pyrocms=3.0-rc2

**Comment by Mastersey** [comment]
Well, i don't know what is happening for me...

**Comment by bloveless** [comment]
What is your environment setup? I might be able to VM your setup and try it again a little later today.

**Comment by RyanThompson** [comment]
Can you post your latest fresh log? Might take a look in your PHP logs too to see if any clues might be in there.

**Comment by Mastersey** [comment]
My httpd error log is always the same:

```
[Fri May 27 19:39:13.484394 2016] [:error] [pid 25164] [client 176.151.214.122:55547] PHP Fatal error:  Uncaught Twig_Error_Loader: Template "theme::errors/500" is not defined (). in /srv/http/pyrocms/vendor/twig/twig/lib/Twig/Loader/Chain.php:115\nStack trace:\n#0 /srv/http/pyrocms/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Chain->getCacheKey('theme::errors/5...')\n#1 /srv/http/pyrocms/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('theme::errors/5...', NULL)\n#2 /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('theme::errors/5...', NULL)\n#3 /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\\Bridge->loadTemplate('theme::errors/5...')\n#4 /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Engine/Twig.php(90): TwigBridge\\Engine\\Compiler->load('theme::errors/5...')\n#5 /srv/http/pyrocms/bootstrap/cache/compiled.php(14586): TwigBridge\\Engine\\Twig->get('theme::errors/5...', Array)\n#6 /srv/http/pyrocms/bootstrap/cache/compiled.php(14574): Illuminate\\View\\View->getContents()\n#7 /srv/http/pyrocms/boo in /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Engine/Compiler.php on line 101, referer: http://mastersey.net/pyrocms/public/installer/finish
[Fri May 27 19:39:13.485986 2016] [:error] [pid 25164] [client 176.151.214.122:55547] PHP Fatal error:  Uncaught Twig_Error_Loader: Template "theme::errors/500" is not defined (). in /srv/http/pyrocms/vendor/twig/twig/lib/Twig/Loader/Chain.php:115\nStack trace:\n#0 /srv/http/pyrocms/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Chain->getCacheKey('theme::errors/5...')\n#1 /srv/http/pyrocms/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('theme::errors/5...', NULL)\n#2 /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('theme::errors/5...', NULL)\n#3 /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\\Bridge->loadTemplate('theme::errors/5...')\n#4 /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Engine/Twig.php(90): TwigBridge\\Engine\\Compiler->load('theme::errors/5...')\n#5 /srv/http/pyrocms/bootstrap/cache/compiled.php(14586): TwigBridge\\Engine\\Twig->get('theme::errors/5...', Array)\n#6 /srv/http/pyrocms/bootstrap/cache/compiled.php(14574): Illuminate\\View\\View->getContents()\n#7 /srv/http/pyrocms/boo in /srv/http/pyrocms/vendor/rcrowe/twigbridge/src/Engine/Compiler.php on line 101, referer: http://mastersey.net/pyrocms/public/installer/finish
```

```
[root@vps244305 http]# pacman -Q | grep php
php 7.0.7-1
php-apache 7.0.7-1
php-gd 7.0.7-1
php-mcrypt 7.0.7-1
php-sqlite 7.0.7-1
phpmyadmin 4.6.1-1
```

I'm not an advanced user like you, so i can share my ssh logins if you want... i have nothing to hide ^_^

**Comment by RyanThompson** [comment]
And you confirmed the file is correct? Make sure to clear your opcache if enabled.

**Comment by Mastersey** [comment]
Sorry, but i don't know where to find the Evaluator.php.
I have a basic configuration (i think) of php. I don't know what's opcache so it's maybe disabled.

**Comment by RyanThompson** [comment]
Restart your server - that will clear opcache. 

The file should be located here:

`{pyro}/vendor/anomaly/streams-platform/src/Support/Evaluator.php`

**Comment by Mastersey** [comment]
Ok thanks, they was the same, no difference in Evaluator.php. To be sure, i replaced it.
After restart and new call of the page "pyrocms/public/installer/finish", still same error while "seeding" .

**Comment by RyanThompson** [comment]
Ah, you can’t quite jump back to the URL directly if that’s what you’re doing. To avoid reinstall form - do this:

Delete all tables from database. 
Mark .env INSTALLED as false

Go to installer/install

**Comment by RyanThompson** [comment]
Also I pushed a fix - won’t help you much but the 404 / 500 pages will display correctly now when the system is uninstalled.

**Comment by Mastersey** [comment]
To be sure, i reinstalled everything again (without clear composer cache), and... still the same problem. For sure, i forgot to install something in my system... 
I'll maybe stop bother you and find something easier for my use.

**Comment by RyanThompson** [comment]
@Mastersey I appreciate you helping track this down today. 

I _did_ get to a deeper root of the problem: https://github.com/anomalylabs/streams-platform/commit/21ab83977245c1d2ad1374b6bb80192e0c834641

I think this was ending up messing up the most. Very odd you ran into this but if you wouldn't mind, checking it out again and see if it's resolved. I've had many reports of successful installs now (phew).

Sorry again for the trouble but thanks for the help!

**Comment by Mastersey** [comment]
@RyanThompson I'm glad you found something to improve !

But, in my case, i still get the same error, even after a fresh install via composer (after a cache clear, empty DB and reboot server).
Btw, i don't see any error in my httpd error log. But the installation process still stuck at "Seeding : Page Modules" step. Always.

**Comment by RyanThompson** [comment]
Damn.. I wish I could login to your system lol! My buddy tried with PHP 7.0.7 too and it all worked! Im stumped. 

At this point.. You might be able to just run `php artisan module:reinstall users --seed`

**Comment by RyanThompson** [comment]
Then login as normal - that will at least seed your users and roles needed (everything else is optional really).

**Comment by Mastersey** [comment]
Hello @RyanThompson :-)

> [root@vps244305 pyrocms]# php artisan module:reinstall users --seed
> Users Module uninstalled successfully!
> Users Module installed successfully!

But i don't know what to do after...
I send you my login, if you want to try by yourself (i'm sure you will find something i forgot...)

**Comment by rgogulakrishnan** [comment]
I am also getting the same error...

**Comment by RyanThompson** [comment]
@rgogulakrishnan what's your environment like? What do you and @Mastersey have in common? 

Can you post your .env files here (remove any private information) and let us know about your system's environment?

**Comment by incraigulous** [comment]
I'm getting the same exact error with the same exact log info as reported by @Mastersey. I am running laravel valet with no changes to pyro's .env file.

**Comment by incraigulous** [comment]
@RyanThompson I just tried install home homestead on a totally different iMac and got the same exact error.

**Comment by rgogulakrishnan** [comment]
Refer #3805 to fix the issue.

**Comment by incraigulous** [comment]
That worked! Thanks so much!
