### ISSUE TITLE
[3.1 Files-Module] Installation Fails with error

### ISSUE THREAD

**Issue by HolyMarcell** [pyrocms/pyrocms#3832]
Hey,

Installing a fresh 3.1 copy via composer and "artisan install" (or with the webinstaller for that matter) failes:

```
[2016-09-07 21:38:20] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class Anomaly\FilesModule\File\FileModel contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Anomaly\FilesModule\File\Contract\FileInterface::entry)' in /home/holy/Host/cmi/pyrocms/core/anomaly/files-module/src/File/FileModel.php:275
Stack trace:
#0 {main}  
```

Rerunning the installer after that produces no errors but leaves the files-module broken:

"Files -> Upload -> "Images" or "Documents" 

errors out with 500 and the following log:

```
QueryException in Connection.php line 761:
SQLSTATE[42000]: Syntax error or access violation: 1055 'cmi.default_files_files.created_at' isn't in GROUP BY (SQL: select count(`default_files_files`.`id`) as aggregate from `default_files_files` where `id` in (0) and `default_files_files`.`deleted_at` is null group by `default_files_files`.`id` order by `updated_at` asc, `created_at` asc)
```

[Stack Trace]

```
PDOException in PDOConnection.php line 79:
SQLSTATE[42000]: Syntax error or access violation: 1055 'cmi.default_files_files.created_at' isn't in GROUP BY
```

[Stack Trace]

```

PDOException in PDOConnection.php line 77:
SQLSTATE[42000]: Syntax error or access violation: 1055 'cmi.default_files_files.created_at' isn't in GROUP BY
```

[Stack Trace]

[stack_trace.zip](https://github.com/pyrocms/pyrocms/files/460408/stack_trace.zip)

Full Stacktrace appended as HTML File (as shown in Debug-Screen from Pyrocms)

**Comment by RyanThompson** [comment]
This has been fixed in the latest Streams-Platform in the 1.1 branch. I don't believe it existing before then.


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by HolyMarcell** [comment]
Sorry, but I don't know what that means. Because the bug persists on a fresh install via "composer create-project pyro/pyro" copy and even if I do a git clone of the pyrocms repo and install everything. How do I aquire the latest stream-platform?

**Comment by RyanThompson** [comment]
Can you try a fresh installation? Delete your current working directory and create-project again. Try running `composer clear-cache` first as well.

**Comment by HolyMarcell** [comment]
This sadly didn't work.

New Folder,
New Database,
composer clear-cache,
composer self-update // from 1.0.3 to current stable 1.2
composer create-project p/p
php artisan install -> Results in the files-module-error 
php artisan install -> Finnishes Installation

File-Upload still shows the  500 error :/

After that I tried 

composer update,
removing installer from composer.json
composer update

but still the Problem persists.

Regards,
Tristan

**Comment by RyanThompson** [comment]
What version of MySQL are you running?

**Comment by RyanThompson** [comment]
Sorry just saw that (on my phone).. Let me do some digging.

**Comment by HolyMarcell** [comment]
Ok, for now I fixed the Problem by Upgrading:

MySQL: to 5.7 and
PHP to version 7.0

I believe the MySQL-Upgrade to be the thing that fixed the problem so far, but a quick look over my clients servers shows that most of them run MySQL versions below 5.7 where the problem occured.

The "GROUP BY" change made by MySQL between versions 5.6 and 5.7 (see: https://craftcms.stackexchange.com/questions/12084/getting-this-sql-error-group-by-incompatible-with-sql-mode-only-full-group-by/12106 fist comment) doesn't seem to be backwards compatible.

--

Disclaimer: I cannot prove anything ;)

**Comment by RyanThompson** [comment]
Im sorry I didn't update this but another community member pointer out that by updating your config to strict = false for the DB configuration.. It fixes it as well!

I'm glad you got this resolved though. Onward!

**Comment by W1ll-1-am** [comment]
Hi, I seem to be getting this error on install too.
It occurs just after the files module trys to install.
[2016-10-11 10:04:23] local.ERROR: ReflectionException: Method Anomaly\Streams\Platform\Stream\Event\StreamWasUpdating::handle() does not exist in /home/william/work/aptana/pyrocms/vendor/laravel/framework/src/Illuminate/Container/Container.php:553

Pyrocms Version 3.1.1
PHP Version - 7.0
MySQL Version - 5.7.15

Any idead what may be causing this @RyanThompson  ?
