### ISSUE TITLE
[URL FT] Issues grabbing the relative URL

### ISSUE THREAD

**Issue by calebsmithdev** [pyrocms/pyrocms#4537]
Inputting text into the URL FT like `/test` is throwing an error: `"Method Anomaly\UrlFieldType\UrlFieldTypePresenter::__toString() must not throw an exception, caught BadMethodCallException: Method formatScheme does not exist."`

If I throw in a full URL, like `https://test.com` then it renders fine. 

The field works as expected on one site with newly created Fields, but causing issues sitewide on an older site with existing fields. Updated all packages.

**Comment by calebsmithdev** [comment]
Identified and pushed to be fixed in https://github.com/anomalylabs/url-field_type/pull/10 - closing this out.

**Comment by fryiee** [comment]
I've moved anomalylabs/url-field_type#10 from a PR on the URL field type to streams-platform directly. https://github.com/anomalylabs/streams-platform/pull/440

**Comment by fryiee** [comment]
Recommend downgrading to 2.1.5 until fixed if in production or similar.

**Comment by RyanThompson** [comment]
This should be resolved.

**Comment by fryiee** [comment]
@RyanThompson your patch did not resolve this issue. I have opened a new PR on the UrlFieldType that utilises the correct method: https://github.com/anomalylabs/url-field_type/pull/11
