### ISSUE TITLE
WYSIWYG removes empty lines from code blocks

### ISSUE THREAD

**Issue by drmonkeyninja** [pyrocms/pyrocms#4995]
**Describe the bug**
Redactor is removing empty lines which causes issues when using the code format to insert example code.

**To Reproduce**
1. Go to a WYSIWYG field
2. Use the 'Code' format to insert a code block
3. Add some text with an empty line in the middle
4. Save, the empty line will have been removed

**Expected behavior**
New lines in code blocks should be persisted.

For example:

```html
<pre>
$foo = 'bar';

echo $foo;</pre>
```

**Screenshots**

![Control_Panel_›_Create](https://user-images.githubusercontent.com/357623/60353539-2382f180-99c2-11e9-966c-da18a7355f49.png)

![Control_Panel_›_Create](https://user-images.githubusercontent.com/357623/60353631-5f1dbb80-99c2-11e9-9845-3c84ff52fa8a.png)

**Additional context**
I'm not sure if this resolves the issue, but there appears to be a `removeNewLines` option in Redactor that I suspect will resolve this: https://imperavi.com/redactor/docs/settings/clean/#s-removenewlines

**Comment by RyanThompson** [comment]
Try this out: https://github.com/anomalylabs/wysiwyg-field_type/commit/fb1e6acbf72b286b6104fd332dd7164660d3ca90

Should fix it - there's an .env param you can set defaults globally as well.

**Comment by drmonkeyninja** [comment]
@RyanThompson I have updated to `3.1.18` on a fresh install of Pyro but am still having the same issue of new lines being removed. I've tried toggling the configuration options of the field but they don't appear to have any affect.
